server:
  port: 10000

lzx:
  idgenerator:
    mode: snowflake
    datacenter: 1
    worker: 1
spring:
  application:
    name: ZX-SECURITY
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://47.93.225.222:3306/lzx_test?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-handlers-package: zx.security.util.mybatisPlus
  global-config:
    db-config:
      logic-not-delete-value: false
      logic-delete-value: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
